apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
  - name: online-inference
    image: rtmlrtx/online-inference:v2
    ports:
    - containerPort: 8080
    resources:
        requests:
          memory: "1Gi"
          cpu: "200m"
        limits:
          memory: "5Gi"
          cpu: "500m"
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 5