apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels: 
    app: online-inference
spec:
  containers:
  - name: online-inference
    image: rtmlrtx/online-inference:v1 
    ports:
    - containerPort: 8080
    resources:
        requests:
          memory: "1Gi"
          cpu: "200m"
        limits:
          memory: "5Gi"
          cpu: "500m"