apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replicaset
  labels:
    app: online-inference
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: online-inference
  template:
    metadata:
      name: online-inference-replicaset
      labels:
        app: online-inference
    spec:
      containers:
        - name: online-inference
          image: rtmlrtx/online-inference:v1
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "5Gi"
              cpu: "500m"